### ISSUE TITLE
setState warning on server - potential fix?

### ISSUE THREAD

**Issue by reactor81** [robrichard/relay-query-lookup-renderer#3]
I find that I am getting the following warning: Warning: setState(...): Can only update a mounting component. This usually means you called setState() outside componentWillMount() on the server. This is a no-op. Please check the code for the ReactRelayQueryRenderer component.

It seems to be caused by the setState inside onNext . Line 211 this.setState({readyState});   

If I wrap this in a if (this._mounted) is seems to work okay, without the warning:
`if (this._mounted) {
        this.setState({readyState});
}`

I'm not 100% sure why this fix helps, or if it is a correct fix. My app *seems* to be okay after this fix and no warning is generated. If this fix is good, should it also be added a few lines above in onError? (Line 188)

Thanks!

**Comment by robrichard** [comment]
Sorry for the late response. I've seen this happen if there is an error rendering inside your `render` prop. Is that the case?

**Comment by klinyecviktor** [comment]
Have the same issue on server too. It works correctly - components are rendered. Looks like after we get the data it start to update the component, though I'm not sure.

**Comment by robrichard** [comment]
Are you using this for server side rendering with `ReactDOMServer.renderToString` or similar?

**Comment by klinyecviktor** [comment]
@robrichard Yeah
Using it for SSR:
`import { renderToString } from 'react-dom/server'`

And I have the same warning:
`Warning: setState(...): Can only update a mounting component. This usually means you called setState() outside componentWillMount() on the server. `

**Comment by robrichard** [comment]
You need to ensure that all of the data has been already fetched in is present in the Relay Store before rendering, or else this component will try to render and update. That means manually fetching your query before rendering. And in that case it would be better to use [relay-context-provider](https://github.com/robrichard/relay-context-provider) on the server so you don't add the overhead of looking up the data you need. In my apps I use `relay-context-provider` on the server and `relay-query-lookup-renderer` on the client, when I will either be rendering the same data that was rendered server side or generating new variables to render client side.

Follow the example here: https://github.com/robrichard/relay-context-provider

**Comment by klinyecviktor** [comment]
@robrichard 
I've modified the relay `Environment` in a way I don't have to get the `rootQuery` and the `variables` - all I need is just to wait for the end of fetching and then rerender with the data I have
This gives me a way of handling the case when there are nested `QueryRenderer`s (I know it's not a good practice of nesting them, though it might happen, that I will need it)
That is why I do not use `relay-context-provider` and I thought may be you know other solutions of handling this error (setting `NODE_ENV` to `production` will just silence this error)

**Comment by robrichard** [comment]
@klinyecviktor I think I understand now. Are you expecting the lower nested QueryRenderer to be fully rendered with their data on the server, or should they only fetch and render on the client? For the former, you will need to make sure you prefetch all of the data for every QueryRenderer before calling `renderToString`. For the latter, maybe you can do something like this to make sure it does attempt to fetch additional data asynchronously on the server

```js
class MyNestedComponent extends React.Component {
  constructor(props) {
    super(props)
    this.state = { isClient: false };
  }
  componentDidMount() {
    // only called on client
    this.setState({isClient: true});
  }
  render() {
    if (!this.state.isClient) {
      return null;
    }
    return <QueryRenderer .... />;
  }
}
```

**Comment by klinyecviktor** [comment]
@robrichard The first one - I want to fully render all the nested QueryRenderers.
Thanks a lot for example.
