### ISSUE TITLE
PR is merged

### ISSUE THREAD

**Issue by shahankit** [robrichard/relay-query-lookup-renderer#6]
The mentioned PR in Readme is merged. But still the `QueryRenderer` from react-relay package does not support caching. Also the current package is not working because the component is unmounted, can you add some documentation to README as to how to retain the component so that lookup code is executed in `componentWillReceiveProps`.

**Comment by robrichard** [comment]
The PR in the Readme was not merged: (https://github.com/facebook/relay/pull/1760). This package doesn't currently retain it's data indefinitely. There was discussion about that here: https://github.com/robrichard/relay-query-lookup-renderer/issues/5
