### ISSUE TITLE
Top level fragments are queried again even if they are already retained

### ISSUE THREAD

**Issue by eav** [robrichard/relay-query-lookup-renderer#9]
thanks for the handy workaround of lookup and retain but I noticed that when I execute the query bellow several times but with different params all query is sent out. 

```
query routerPageBlogQuery($count: Int!, $cursor: String) {
    blogPage {
      id
      name
      content
    }
    blogPosts(first: $count, after: $cursor) {
      edges {
        cursor
        node {
          id
          name
        }
      }
    }
  }
```

as you can see blogPage doesn't require any params so basically it can be excluded from subsequent requests, is it possible to support that?

**Comment by robrichard** [comment]
The “query diffing” feature of Relay classic is not supported with Relay modern. All queries are static to allow support for persisting at build time. In your case I think it would be better to break the two parts of the query into fragments and use a refetch container to conditionally fetch the part of the query you want
